In [103]:
import pandas as pd
import numpy as np
import sys
sys.path.append('..')

In [104]:
top_tokens=pd.read_csv('../raw_data/top_token_red.csv')
top_tokens

,wine_cluster_1,weights_1,wine_cluster_2,weights_2,wine_cluster_3,weights_3,wine_cluster_4,weights_4,wine_cluster_5,weights_5,wine_cluster_6,weights_6,wine_cluster_7,weights_7,wine_cluster_8,weights_8,wine_cluster_9,weights_9,wine_cluster_10,weights_10
0,tobacco,1212.239543,sweet,1848.455264,bright,1439.824012,cassis,1399.422635,dry,1755.308820,vanilla,1719.031774,herbal,1693.339908,fruit,1886.470523,smooth,1403.730238,light,1944.668332
1,balanced,1034.345223,earthy,1113.823569,leather,1336.991954,blackberry,1024.280878,currant,1396.030748,raspberry,1259.905671,berry,1108.037075,wood,1440.991645,licorice,1214.131888,tannic,833.356003
2,chocolate,676.840402,cherry,485.563395,pepper,1074.957173,herb,862.270162,cola,1340.738413,cherry,1072.589502,spicy,911.785788,tannin,1393.793323,tannin,465.366755,fruit,520.986994
3,fruit,487.776794,soft,441.738188,cherry,876.169123,fruit,536.717667,cherry,795.281673,oak,988.775099,plum,845.636308,ripe,1292.165963,cherry,419.292154,cherry,369.087060
4,cherry,454.770473,fruit,431.156588,tannin,714.187476,tannin,533.404826,blackberry,718.355148,fruit,780.034223,fruit,620.946476,acidity,1288.422235,fruit,360.884751,fresh,307.888979
5,tannin,426.529642,raspberry,314.898898,berry,693.554994,oak,530.698825,tannin,627.592947,spice,664.580823,oak,364.596383,fruity,1195.137705,blackberry,343.452022,acidity,260.471370
6,spice,414.819808,oak,305.581499,fruit,605.398516,cherry,484.156882,rich,527.241898,plum,505.438724,cherry,307.988022,rich,1026.512883,ripe,330.094321,raspberry,234.189619
7,plum,307.213093,blackberry,305.331581,spice,604.488273,chocolate,419.074275,oak,490.610572,tannin,500.707891,tannin,298.410973,soft,641.836623,spice,312.862199,berry,211.165396
8,blackberry,280.917180,ripe,302.820284,acidity,565.190035,ripe,330.951403,tannic,485.518911,fresh,297.912756,earthy,256.150134,berry,552.236338,plum,275.299935,herb,207.162531
9,berry,275.614316,berry,291.635244,coffee,484.940308,spice,321.966645,fruit,424.452768,coffee,295.122294,spice,239.514651,fresh,498.545958,berry,265.320324,tannin,192.283783
10,rich,251.675504,tannin,285.423704,herb,425.506877,plum,277.644639,acidity,406.878697,ripe,290.281733,tannic,228.201486,cherry,487.867745,chocolate,249.833621,spice,173.787366
11,acidity,247.429958,plum,265.881706,fresh,400.128534,rich,262.568976,spice,350.409869,soft,276.243003,acidity,212.774835,spice,474.842171,pepper,228.682515,plum,171.035882
12,ripe,246.064004,spice,250.217589,raspberry,382.469529,soft,224.064565,ripe,339.754661,acidity,249.832907,fresh,203.020752,plum,384.554602,oak,195.701361,soft,158.932827
13,pepper,193.758340,chocolate,223.820571,plum,321.027531,berry,219.739989,pepper,306.482296,chocolate,247.050456,herb,151.963568,blackberry,320.748233,rich,195.283967,fruity,153.090716
14,coffee,187.003696,rich,178.943824,ripe,291.223869,tannic,170.678495,soft,290.238176,berry,243.752528,dry,150.622348,currant,258.843552,herb,191.025911,oak,123.174439
15,leather,186.580202,acidity,164.741905,blackberry,275.253150,coffee,162.100425,raspberry,284.889169,herb,242.623217,raspberry,146.498935,dry,244.693792,soft,190.569871,pepper,121.209473
16,oak,183.307022,tannic,109.230796,licorice,232.372871,acidity,128.841399,chocolate,281.078853,rich,187.830574,blackberry,134.488651,balanced,223.525507,raspberry,145.401297,ripe,111.937426
17,soft,151.164396,herb,98.977913,tobacco,223.309959,pepper,122.584211,sweet,236.493749,blackberry,174.040937,pepper,121.314850,smooth,172.513697,coffee,144.910561,dry,110.051024
18,herb,151.019727,spicy,93.498010,soft,206.525206,currant,99.198059,spicy,194.496077,pepper,152.484842,ripe,109.857986,spicy,170.781206,tobacco,136.260892,bright,107.786613
19,fresh,125.379827,pepper,89.060101,oak,139.856346,fresh,95.328199,licorice,162.043819,sweet,114.569368,chocolate,105.103686,bright,122.022026,currant,132.862905,currant,78.528837
20,vanilla,117.929462,fruity,79.828977,chocolate,107.871618,dry,94.877748,berry,149.932520,wood,60.123933,currant,81.696302,oak,95.830663,acidity,95.375435,blackberry,69.065444
21,dry,107.707414,dry,75.557394,earthy,106.310299,vanilla,83.774897,plum,135.032912,cola,37.637166,coffee,53.739631,chocolate,47.998348,spicy,93.763995,chocolate,67.417284
22,currant,101.113120,coffee,45.463423,cola,104.907216,sweet,76.329735,herb,91.970457,bright,10.046066,leather,52.441622,herb,0.152703,vanilla,71.923154,balanced,52.950498
23,licorice,87.399291,fresh,44.844284,currant,81.875891,licorice,38.418280,fruity,78.419210,light,4.304415,soft,44.875607,coffee,0.136965,fresh,64.801772,rich,43.103750
24,raspberry,76.113530,vanilla,38.871510,balanced,72.827564,spicy,34.427812,balanced,72.624761,licorice,3.592369,cassis,38.106388,pepper,0.121666,tannic,51.436890,spicy,37.290366
25,spicy,72.385470,smooth,4.917949,spicy,59.537411,earthy,0.117288,fresh,0.100007,fruity,0.286860,tobacco,14.243541,sweet,0.116422,leather,40.633230,earthy,19.176342
26,tannic,53.115367,currant,3.321797,rich,50.901456,raspberry,0.113496,vanilla,0.100006,currant,0.238652,vanilla,8.984964,tannic,0.100309,cassis,1.029552,cola,0.100006
27,cassis,48.380948,cola,0.384015,smooth,1.297665,leather,0.100043,smooth,0.100006,smooth,0.100118,rich,6.479065,raspberry,0.100021,fruity,0.434962,smooth,0.100006
28,sweet,48.361329,leather,0.100006,vanilla,0.523967,wood,0.100006,tobacco,0.100006,dry,0.100011,bright,0.377039,light,0.100005,sweet,0.372862,coffee,0.100005
29,earthy,27.167479,licorice,0.100005,dry,0.203936,tobacco,0.100006,leather,0.100005,spicy,0.100007,fruity,0.281220,vanilla,0.100004,dry,0.279895,sweet,0.100005

In [105]:
selected_tokens_list = ['cherry', 'fruit', 'tannin']

In [106]:
cluster_ranking={}
for i in range(0,10):
    cluster_ranking[f'wine_cluster_{i+1}']=0
    for token in selected_tokens_list:
        if token in top_tokens.iloc[:,i*2].to_list():
            cluster_ranking[f'wine_cluster_{i+1}']+=top_tokens[f'weights_{i+1}'][top_tokens[f'wine_cluster_{i+1}']==token].sum()

In [107]:
cluster_ranking

{'wine_cluster_1': 1369.0769090103029,
 'wine_cluster_2': 1202.1436870732748,
 'wine_cluster_3': 2195.7551142880143,
 'wine_cluster_4': 1554.2793757182847,
 'wine_cluster_5': 1847.3273875793086,
 'wine_cluster_6': 2353.3316159120677,
 'wine_cluster_7': 1227.345471281048,
 'wine_cluster_8': 3768.131591772297,
 'wine_cluster_9': 1245.5436599655854,
 'wine_cluster_10': 1082.3578369995976}

In [108]:
top_clusters=pd.DataFrame(list(cluster_ranking.items())).sort_values(1, ascending=False)[0][0:2].to_list()
top_clusters.append('ID')
top_clusters

['wine_cluster_8', 'wine_cluster_6', 'ID']

In [109]:
lda_wine_cluster=pd.read_csv('../raw_data/lda_wine_cluster_prob_red.csv', index_col=0)
lda_wine_cluster

,wine_cluster_1,wine_cluster_2,wine_cluster_3,wine_cluster_4,wine_cluster_5,wine_cluster_6,wine_cluster_7,wine_cluster_8,wine_cluster_9,wine_cluster_10,ID
0,0.034688,0.034688,0.034689,0.034687,0.034687,0.034687,0.034691,0.687765,0.034729,0.034688,0
1,0.045295,0.045329,0.045295,0.045297,0.045302,0.045293,0.592280,0.045293,0.045294,0.045322,3
2,0.030068,0.030069,0.030071,0.030078,0.030069,0.030076,0.729361,0.030069,0.030068,0.030071,4
3,0.028236,0.028197,0.746185,0.028198,0.028196,0.028196,0.028196,0.028202,0.028196,0.028199,5
4,0.627963,0.041342,0.041340,0.041339,0.041331,0.041342,0.041336,0.041336,0.041338,0.041332,9
...,...,...,...,...,...,...,...,...,...,...,...
68050,0.040900,0.040899,0.040904,0.040899,0.040899,0.040905,0.040899,0.631890,0.040898,0.040906,111526
68051,0.030718,0.030720,0.593503,0.030721,0.030718,0.030720,0.030715,0.030721,0.160747,0.030718,111527
68052,0.035795,0.035788,0.035809,0.677775,0.035797,0.035789,0.035787,0.035785,0.035888,0.035788,111528
68053,0.054584,0.054582,0.054587,0.054586,0.054583,0.508738,0.054580,0.054594,0.054584,0.054582,111529
68054,0.039197,0.647214,0.039197,0.039198,0.039197,0.039202,0.039195,0.039204,0.039197,0.039199,111532

In [110]:
pred_df=pd.read_csv('../raw_data/predictions.csv')
pred_df

      match_wine  total_distance     ID
0          11525        4.572466  11525
1            759        4.572466    759
2           9200        4.592706   9200
3          21972        4.624287  21972
4          46970        4.651933  46970
...          ...             ...    ...
1215       41527        6.961153  41527
1216        5503        6.963735   5503
1217       35530        6.968062  35530
1218       24360        6.968062  24360
1219       66442        7.007715  66442

[1220 rows x 3 columns]

In [112]:
lda_selected=pd.merge(pred_df, lda_wine_cluster[top_clusters], on="ID", how="inner")
lda_selected

     match_wine  total_distance     ID  wine_cluster_8  wine_cluster_6
0           759        4.572466    759        0.584188        0.046272
1          9200        4.592706   9200        0.451383        0.060958
2         46970        4.651933  46970        0.038414        0.038417
3         60467        4.656436  60467        0.035373        0.035383
4           339        4.656436    339        0.220402        0.436178
..          ...             ...    ...             ...             ...
718       44623        6.935755  44623        0.048904        0.048880
719       41527        6.961153  41527        0.034943        0.034939
720        5503        6.963735   5503        0.668219        0.036860
721       24360        6.968062  24360        0.053540        0.053543
722       66442        7.007715  66442        0.042681        0.042688

[723 rows x 5 columns]

In [113]:
lda_selected['total_cluster']=lda_selected.iloc[:,3]+lda_selected.iloc[:,4]
lda_selected

,match_wine,total_distance,ID,wine_cluster_8,wine_cluster_6,total_cluster
0,759,4.572466,759,0.584188,0.046272,0.630460
1,9200,4.592706,9200,0.451383,0.060958,0.512341
2,46970,4.651933,46970,0.038414,0.038417,0.076831
3,60467,4.656436,60467,0.035373,0.035383,0.070756
4,339,4.656436,339,0.220402,0.436178,0.656580
...,...,...,...,...,...,...
718,44623,6.935755,44623,0.048904,0.048880,0.097784
719,41527,6.961153,41527,0.034943,0.034939,0.069882
720,5503,6.963735,5503,0.668219,0.036860,0.705079
721,24360,6.968062,24360,0.053540,0.053543,0.107083
722,66442,7.007715,66442,0.042681,0.042688,0.085370

In [114]:
lda_selected.sort_values(by='total_cluster', ascending=False)

,match_wine,total_distance,ID,wine_cluster_8,wine_cluster_6,total_cluster
380,65527,5.842855,65527,0.767805,0.025796,0.793602
37,25696,4.963208,25696,0.754203,0.027305,0.781508
154,8811,5.424231,8811,0.027435,0.753098,0.780533
605,52265,6.349498,52265,0.029109,0.738230,0.767339
333,13807,5.766697,13807,0.030383,0.726648,0.757030
...,...,...,...,...,...,...
79,31217,5.193017,31217,0.028285,0.028288,0.056574
403,43978,5.884440,43978,0.028216,0.028231,0.056448
132,8808,5.379961,8808,0.027739,0.027739,0.055478
229,20989,5.610786,20989,0.027115,0.027117,0.054232
293,51591,5.712909,51591,0.024335,0.024352,0.048686

In [127]:
lda_selected['distance_rank']=lda_selected['total_distance'].rank(ascending=False)
lda_selected['cluster_rank']=lda_selected['total_cluster'].rank(ascending=True)
lda_selected['final_rank']=lda_selected['distance_rank']+lda_selected['cluster_rank']
lda_selected.sort_values(by='final_rank', ascending=False, inplace=True)
lda_selected

,match_wine,total_distance,ID,wine_cluster_8,wine_cluster_6,total_cluster,distance_rank,cluster_rank,final_rank
37,25696,4.963208,25696,0.754203,0.027305,0.781508,686.0,722.0,1408.0
34,25093,4.950404,25093,0.701933,0.033118,0.735051,689.5,713.0,1402.5
4,339,4.656436,339,0.220402,0.436178,0.656580,719.5,662.0,1381.5
27,17794,4.929809,17794,0.643208,0.039642,0.682849,696.0,682.0,1378.0
52,4823,5.061996,4823,0.035489,0.680586,0.716075,671.0,705.0,1376.0
...,...,...,...,...,...,...,...,...,...
698,22632,6.709829,22632,0.033108,0.033107,0.066215,25.0,50.0,75.0
696,47735,6.661556,47735,0.033029,0.033029,0.066059,27.0,46.0,73.0
688,43463,6.647934,43463,0.032120,0.032122,0.064241,35.0,37.0,72.0
670,50389,6.565871,50389,0.030292,0.030288,0.060580,53.0,18.0,71.0
707,60787,6.781732,60787,0.032643,0.032648,0.065291,16.0,43.0,59.0

In [148]:
final_list=lda_selected.iloc[0:10]['match_wine'].tolist()
final_list

[25696, 25093, 339, 17794, 4823, 44091, 759, 55670, 43304, 21697]

In [152]:
preprocessed.iloc[final_list]

,ID,country,description,points,price,province,title,winery,type,region,variety_adj
25696,28152,France,"A smooth wine, rich for the vintage, with blac...",90,140.0,Bordeaux,ChÃ¢teau Ausone 2007 La Chapelle d'Ausone (Sa...,ChÃ¢teau Ausone,red,Saint-Ã‰milion,Bordeaux-style Red
25093,27474,Argentina,"Dry, fresh aromas of red fruits set up a tight...",86,12.0,Mendoza Province,Navarro Correas 2012 ColecciÃ³n Privada Cabern...,Navarro Correas,red,Mendoza,Cabernet Sauvignon
339,365,Australia,The Taylor family selected Clare Valley for it...,95,60.0,South Australia,Wakefield 2013 St. Andrews Single Vineyard Rel...,Wakefield,red,Clare Valley,Shiraz
17794,19335,US,This wine offers very ripe and vivid fruit in ...,88,50.0,California,Domaine Anderson 2013 Estate Bottled Pinot Noi...,Domaine Anderson,red,Anderson Valley,Pinot Noir
4823,5200,US,The winery's Willamette Valley cuvÃ©e is right...,90,28.0,Oregon,Raptor Ridge 2012 Pinot Noir (Willamette Valley),Raptor Ridge,red,Willamette Valley,Pinot Noir
44091,48879,Austria,Juicy blueberry and ripe blackberry dominate n...,83,15.0,Burgenland,Salzl Seewinkelhof 2013 Zweigelt (Burgenland),Salzl Seewinkelhof,red,Burgenland,Zweigelt
759,801,US,Made entirely from Syrah grown on its property...,90,50.0,California,Deerfield Ranch NV Tawny Estate Syrah (Sonoma ...,Deerfield Ranch,red,Sonoma Valley,Shiraz
55670,62419,Portugal,From a small Lisboa vineyard owned by Rocim's ...,92,35.0,Lisboa,Herdade do Rocim 2013 Vale da Mata Reserva Red...,Herdade do Rocim,red,Lisboa,Portuguese Red
43304,47950,US,Totally delicious and so easy to like for its ...,88,15.0,California,Wente 2007 Sandstone Merlot (Arroyo Seco),Wente,red,Arroyo Seco,Merlot
21697,23684,France,"Bright and fruity, this wine is attractive in ...",87,10.0,Bordeaux,ChÃ¢teau Lacaussade Saint-Martin 2015 Trois Mo...,ChÃ¢teau Lacaussade Saint-Martin,red,Blaye CÃ´tes de Bordeaux,Bordeaux-style Red

In [154]:
X_scaled_red = pd.read_csv('../raw_data/X_scaled_red.csv', index_col=0)
X_scaled_red

,country,points,price,province,winery,region,variety_adj,type_red,type_rose,type_spark,type_white
0,-0.24,-0.2,-0.40,-0.262931,0.968039,-1.133721,0.029091,3.0,0.0,0.0,0.0
3,0.12,-0.2,1.60,0.422414,1.388925,2.591860,0.000000,3.0,0.0,0.0,0.0
4,0.00,-0.2,-0.40,0.396552,1.409970,0.502326,0.396364,3.0,0.0,0.0,0.0
5,-0.60,-0.2,-0.36,0.693966,1.485729,2.483721,-0.687273,3.0,0.0,0.0,0.0
9,0.12,-0.2,-0.24,-0.500000,0.049454,0.463953,-1.010909,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
111526,-0.24,0.4,0.92,-0.262931,-1.569907,-1.133721,0.000000,3.0,0.0,0.0,0.0
111527,-0.60,0.4,0.20,0.693966,-1.755623,1.559302,-0.687273,3.0,0.0,0.0,0.0
111528,-0.60,0.4,0.60,0.693966,-0.934368,1.559302,-0.138182,3.0,0.0,0.0,0.0
111529,-0.64,0.4,-0.20,-0.155172,-0.912798,-0.837209,-1.010909,3.0,0.0,0.0,0.0
111532,0.12,0.4,2.00,0.422414,-1.077732,0.655814,0.000000,3.0,0.0,0.0,0.0

In [165]:
X_scaled_red[X_scaled_red['type_red']>0].iloc[2].name

4

In [168]:
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=10000, algorithm='ball_tree', n_jobs=-1)
neigh.fit(X_scaled_red)
distance, indeces = neigh.kneighbors([X_scaled_red.iloc[2]])

/Users/felipedalcin/.pyenv/versions/3.10.6/envs/WineGen/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

In [173]:
indeces[0]

array([    2,  3055, 47592, ..., 56194, 10945,  6731])