In [51]:
import pandas as pd
import numpy as np
import sys
sys.path.append('..')

In [81]:
vectorized_descr_red=pd.read_csv('../raw_data/vectorized_descriptions_red.csv')
pred_df=pd.read_csv('../raw_data/predictions.csv')

In [82]:
# vectorized_descr_red.set_index('ID', inplace=True)
vectorized_descr_red

,acidity,balanced,berry,blackberry,bright,cassis,cherry,chocolate,coffee,cola,...,soft,spice,spicy,sweet,tannic,tannin,tobacco,vanilla,wood,ID
0,0.258328,0.000000,0.250558,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.189653,0.0,0.0,0.0,0
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.381878,0.000000,0.0,0.0,0.0,3
2,0.226639,0.000000,0.000000,0.229029,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.319465,0.0,0.000000,0.000000,0.0,0.0,0.0,4
3,0.242109,0.351533,0.234826,0.000000,0.342767,0.000000,0.000000,0.000000,0.000000,0.0,...,0.292264,0.000000,0.000000,0.0,0.000000,0.177745,0.0,0.0,0.0,5
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.349495,0.428539,0.0,...,0.346304,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68050,0.319976,0.000000,0.000000,0.000000,0.000000,0.000000,0.235782,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,111526
68051,0.211615,0.000000,0.000000,0.000000,0.299595,0.000000,0.311867,0.000000,0.000000,0.0,...,0.255454,0.206276,0.000000,0.0,0.000000,0.155358,0.0,0.0,0.0,111527
68052,0.000000,0.000000,0.000000,0.453222,0.000000,0.326156,0.165241,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,111528
68053,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.423701,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.211069,0.0,0.0,0.0,111529
68054,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.434395,0.000000,0.000000,0.0,...,0.711637,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,111532

In [89]:
pred_df['ID']=pred_df['match_wine']

In [99]:
result=pd.merge(vectorized_descr_red, pred_df, on='ID', how='inner')
result

,acidity,balanced,berry,blackberry,bright,cassis,cherry,chocolate,coffee,cola,...,spicy,sweet,tannic,tannin,tobacco,vanilla,wood,ID,match_wine,total_distance
0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,67,67,5.643213
1,0.000000,0.0,0.000000,0.329461,0.0,0.0,0.000000,0.000000,0.0,0.00000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,132,132,6.342189
2,0.279303,0.0,0.270902,0.000000,0.0,0.0,0.000000,0.340271,0.0,0.00000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,145,145,5.759642
3,0.294297,0.0,0.000000,0.000000,0.0,0.0,0.216859,0.000000,0.0,0.43581,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,170,170,6.030858
4,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.221197,0.000000,0.0,0.00000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,174,174,5.743456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.185519,0.000000,0.0,0.00000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.370501,111227,111227,5.626222
1216,0.000000,0.0,0.261360,0.000000,0.0,0.0,0.000000,0.328286,0.0,0.00000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,111289,111289,5.735466
1217,0.590254,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,111400,111400,5.875915
1218,0.000000,0.0,0.231844,0.000000,0.0,0.0,0.176137,0.000000,0.0,0.00000,...,0.0,0.0,0.000000,0.175487,0.0,0.0,0.000000,111450,111450,6.807190
1219,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.189276,0.000000,0.0,0.00000,...,0.0,0.0,0.345614,0.000000,0.0,0.0,0.000000,111480,111480,5.557810

In [117]:
result.drop(columns=['match_wine', 'total_distance', 'ID']).sum().sort_values(ascending=False)[0:10].index.tolist()

['cherry',
 'fruit',
 'tannin',
 'ripe',
 'acidity',
 'rich',
 'dry',
 'spice',
 'blackberry',
 'raspberry']

In [118]:
pd.merge(vectorized_descr_red, pred_df, on='ID', how='inner').drop(columns=['match_wine', 'total_distance', 'ID']).sum().sort_values(ascending=False)[0:10].index.tolist()

['cherry',
 'fruit',
 'tannin',
 'ripe',
 'acidity',
 'rich',
 'dry',
 'spice',
 'blackberry',
 'raspberry']